Made function writequestion in moodle emulator public
Needed to fix

Fatal error: Access level to qformat_qtex_emulator::writequestion() must
be public (as in class qformat_qtex) in converter/moodle_emulator.php on
line 123